spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${jdbcUrl}
    username: ${jdbcUsername}
    password: ${jdbcPassword}

  config:
    import: optional:file:.env[.yml]
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
server:
  servlet:
    context-path: /api


kakao:
  login:
    restApi: ${restAPI}
    redirectUri: ${redirectUri}

jwt:
  accessExpiration: ${accessExpiration}
  refreshExpiration: ${refreshExpiration}

  secret:
    key: ${secretKey}

frontend:
  url: ${fronendUrl}

springdoc:
  api-docs:
    path: /api-docs

  default-consumes-media-type: application/json
  default-produces-media-type: application/json

  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method           # method 순으로 정렬
    tags-sorter: alpha                  # 태그 알파벳 순 정렬
    try-it-out-enabled: true            # Try it out 버튼
    filter: true                        # 필터 바 표시
    display-request-duration: true      # 요청 소요시간 표시
    enabled: true



